name: deploy to github pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: debounce
        run: sleep 120

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: install dependencies
        run: npm ci

      - name: clean dist folder
        run: rm -rf dist

      - name: build
        run: npm run build
        env:
          VITE_OCR_SPACE_KEY: ${{ secrets.VITE_OCR_SPACE_KEY }}

      - name: add nojekyll file
        run: touch dist/.nojekyll

      - name: setup pages
        uses: actions/configure-pages@v5

      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v4
